#!/usr/bin/env python3
"""
Solution for exercise 27 "makepw" from chapter 6 of "Python Workout" by Reuven M. Lerner
"""

from typing import Callable
import secrets


def create_password_generator(allowed_chars: str) -> Callable[[int], str]:
    """Returns callable that returns passwords of a length passed as a parameter.

    Passwords generated by this callable will contains only characters from
    `allowed_chars`. Method for choosing characters is cryptographically
    secure.

    Args:
        allowed_chars (str): Characters allowed in password generation.

    Returns:
        Callable[[int], str]: Callable accepting password length as a parameter
          and returning password of that length comprised of `allowed_chars`.
    """

    def password_generator(length: int) -> str:
        return "".join(secrets.choice(allowed_chars) for _ in range(length))

    return password_generator


def _main():
    allowed_chars_ = input("Please enter characters allowed in the password: ")
    password_generator = create_password_generator(allowed_chars_)
    length = int(input("Enter the desired length of the password: "))
    password = password_generator(length)
    print(f"Generated password is: {password}")


if __name__ == "__main__":
    _main()
